version: '3.8'

services:
  eureka-server:
    build:
      context: .             # Use root directory
      dockerfile: Dockerfile # Optional if your file is named Dockerfile
    ports:
      - "8761:8761"
    networks:
      - host-access
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_APPLICATION_NAME=eureka-server  # Ensure each instance uses the same service name

networks:
  host-access:
    driver: bridge
